version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - 8080:80

  nginx:
    image: nginx:latest
    container_name: vue-nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/cloud_aggreko.crt:/etc/ssl/certs/cloud_aggreko.crt
      - /etc/ssl/private/cloud_aggreko.key:/etc/ssl/private/cloud_aggreko.key
    ports:
      - 80:80
    depends_on:
      - app
